### ISSUE TITLE
Handle input greater than total number of videos available

### ISSUE THREAD

**Issue by sachapan** [sachapan/getsubs#3]
Current result when 11 is entered:

Please enter the video number or q to exit: 11
Traceback (most recent call last):
  File "/home/sacha/projects/getsubs/getjwsubs.py", line 332, in <module>
    main()
  File "/home/sacha/projects/getsubs/getjwsubs.py", line 328, in main
    webmenu()
  File "/home/sacha/projects/getsubs/getjwsubs.py", line 245, in webmenu
    subtitle = vidslist[int(vidnum)]
               ~~~~~~~~^^^^^^^^^^^^^
IndexError: list index out of range
(venv) FAIL: 1

**Comment by sachapan** [comment]
Resolved.
